# Generated by Django 5.0.2 on 2024-03-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='image_path',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image_path',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
